version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=java_certifications_api
    volumes:
      - certifications_api_pg_data:/bitnami/postgresql

volumes:
  certifications_api_pg_data:
